feature(client/managment):forms, graficos, tablas, get, post  y delete actions.
RodrigoSpano/pig_commander_client pull request #303
Opened 2023-08-20 01:44 UTC by laurenciopaez

2023-08-20 02:21 UTC, RodrigoSpano requested changes
pongo request changes x las dudas pa q no mergeen sin querer, asi arreglas lo de q no se actualiza el estado y lo pusheas a esta pr

2023-08-20 18:04 UTC, RodrigoSpano reviewed
se actualiza en tiempo real?

2023-08-20 18:22 UTC, RodrigoSpano submitted a review, later dismissed

2023-08-20 18:26 UTC, benjapadilla1 approved these changes
Estas loco

2023-08-21 14:29 UTC, Vickyrdz submitted a review, later dismissed

2023-08-21 15:41 UTC, benjapadilla1 approved these changes
Bien pibe

2023-08-21 15:48 UTC, RodrigoSpano approved these changes

2023-08-21 15:58 UTC, merged